ARDUINO_DIR = /usr/share/arduino
ARDUINO_PORT = /dev/ttyACM*

USER_LIB_PATH = ~/Desktop/Lunacats/LunacatsRaspberryPi/2019-2020/Testing/ArduinoSerialTests/ArduinoCode/
BOARD_TAG = uno

include /usr/share/arduino/Arduino.mk
